name: Build IPA

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest   # GitHub 提供云端 macOS 环境
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & Build Web
        run: |
          npm ci
          npm run build || true   # 没 build 脚本就跳过

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable


      - name: Build IPA
        run: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme DrawNix \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build \
            -allowProvisioningUpdates \
            CODE_SIGN_STYLE=Automatic \
            CODE_SIGN_IDENTITY="Apple Development"
          mkdir Payload
          cp -r build/Build/Products/Release-iphoneos/App.app Payload
          zip -r ../../Drawnix.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Drawnix-IPA
          path: Drawnix.ipa
